### ISSUE TITLE
HipChat notification fails when using API token

### ISSUE THREAD

**Issue by jikamens** [havramar/hipchat-notifier-plugin#6]
I'm using an API token rather than a room token. HipChat notification is failing with status code 401 whether I configure the API token in the system configuration or in the individual jenkins job.

**Comment by havramar** [comment]
Is it your personal API token that gives 401?

According to docs 4 types of tokens are valid. 

https://www.hipchat.com/docs/apiv2/auth

I have asked HipChat support about using v1 tokens in v2 API. They said that it should not work, and one must switch to API v2 tokens.

**Comment by jikamens** [comment]
Not a personal API token, rather a token I generated on the API token page at https://quantopian.hipchat.com/admin/api. Are you saying the tokens on that page won't work with API v2? It doesn't say that anywhere on the page, at least not clearly. There is a generic warning at the top that people should use API v2, but it doesn't explicitly say there that the tokens on that page are only for v1.

**Comment by havramar** [comment]
I had the same doubts about that. Support said that one can't simply switch from v1 to v2 and that tokens have different characters length (the latter should not be the problem though). Although it was not straight answer to my question (despite more specific ones after receiving first answer), I just assumed that for v2 we should use v2 tokens.

**Comment by havramar** [comment]
I have updated readme about v1/v2 tokens.
