### ISSUE TITLE
Username?

### ISSUE THREAD

**Issue by johntmyers** [havramar/hipchat-notifier-plugin#9]
Is there a place to configure what username this plugin uses to post? It always shows in HipChat as 'token' as the sender.

**Comment by havramar** [comment]
Are you using your personal API Access token (from https://xxx.hipchat.com/account/api) or room access token (https://xxx.hipchat.com/rooms/tokens/_room_id_) ?

In case of the room access token, when you create one, you specify `label` and it is used as a Sender Name of the message.

**Comment by johntmyers** [comment]
That makes sense, thanks!
